In [1]:
import pandas as pd
from sklearn.preprocessing import LabelBinarizer

In [2]:
df = pd.read_csv("data/train.csv").drop(labels=["Name", "Ticket", "Cabin"], axis=1).dropna()

In [3]:
df = pd.get_dummies(df)

In [4]:
df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,0,1,0,0,1
1,2,1,1,38.0,1,0,71.2833,1,0,1,0,0
2,3,1,3,26.0,0,0,7.9250,1,0,0,0,1
3,4,1,1,35.0,1,0,53.1000,1,0,0,0,1
4,5,0,3,35.0,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,1,0,0,1,0
886,887,0,2,27.0,0,0,13.0000,0,1,0,0,1
887,888,1,1,19.0,0,0,30.0000,1,0,0,0,1
889,890,1,1,26.0,0,0,30.0000,0,1,1,0,0
890,891,0,3,32.0,0,0,7.7500,0,1,0,1,0

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(labels='Survived', axis=1),
                                                    df['Survived'],
                                                    test_size=0.2,
                                                    random_state=42)

In [6]:
from lib.models import LogisticRegression


regr = LogisticRegression()
regr.train(x_train, y_train, max_epochs=50)

/home/vaskers5/projects/my_projects/Educational_Nets/lib/models/baseModel.py:33: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))

In [8]:
from sklearn.linear_model import LogisticRegression as lg
from sklearn.metrics import accuracy_score


sklearn_regr = lg().fit(x_train, y_train)
print(f"Sklearn score is {accuracy_score(sklearn_regr.predict(x_test), y_test)}")
print(f"My score is {accuracy_score(regr.predict(x_test), y_test)}")

Sklearn score is 0.8041958041958042
My score is 0.6433566433566433

/home/vaskers5/miniconda3/envs/env/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/vaskers5/projects/my_projects/Educational_Nets/lib/models/baseModel.py:33: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))